// laravel10_breeze_inertia_vua/resources/js/Pages/Post/Create.vue
<template>
<div class="container">


       <Link  :href="route('posts.index')"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3 text-white">Post List</Link>


   <form @submit.prevent="submit">
                            <div class="mb-4" from-group>
                                <label
                                    for="title"
                                    class="block text-gray-700 text-sm font-bold mb-2">
                                    Title:</label>
                                <input
                                    type="text"
                                    class="from-control"
                                    placeholder="Enter Title"
                                    id="title"
                                    v-model="form.title" />

                            </div>

                            <div class="mb-4">
                                <label
                                    for="body"
                                    class="block text-gray-700 text-sm font-bold mb-2">
                                    Body:</label>
                                <textarea
                                    class="from-control"
                                    v-model="form.body"
                                    placeholder="Enter Body"></textarea>
                            </div>

                            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3 text-white">
                                New Entry
                            </button>

                        </form>
 </div>
</template>

<script setup>
import { useForm,Link } from '@inertiajs/vue3'
const form = useForm({
    title: '',
    body: '',
});
const submit = () => {
  form.post("/posts");
};


</script>

<style>

</style>

// laravel_react_crud/resources/js/Pages/Posts/Create.jsx
import React from 'react'
import { useForm } from '@inertiajs/react'

export default function Create() {

    const { data, setData, post, errors } = useForm({
        title: "",
        body: ""

    })

    function handleSubmit(e) {
        e.preventDefault();
        post(route('posts.store'))
        //alert('Data Sent')
    }
    console.log(data)

    return (
        <div>
            <form onSubmit={handleSubmit}>
                Title: <input type="text" name='title' placeholder='Enter title' value={data.title} onChange={(e) => setData('title', e.target.value)} /> <span>{errors.title}</span> <br />
                Details: <textarea name="body" id="" placeholder='this is textarea' onChange={(e) => setData('body', e.target.value)}>{data.body}</textarea> <span>{errors.body}</span> <br />
                <button type='submit' name='submit'>Submit</button>
            </form>
        </div>
    )
}
